create table proposal
(
    id           int(10) auto_increment comment 'ID'
        primary key,
    content      varchar(50) default '' not null comment '内容',
    add_time     datetime               not null comment '添加时间',
    pid          int         default 0  not null comment '提交人呢',
    photo_one    varchar(50)            null comment '图片1',
    photo_two    varchar(50)            null comment '图片2',
    photo_three  varchar(50)            null comment '图片3',
    photo_four   varchar(50)            null comment '图片4',
    photo_five   varchar(50)            null comment '图片5',
    update_time  datetime               null,
    remark       longtext               null,
    process_id   int                    null comment '处理人id',
    process_name varchar(50)            null comment '处理人',
    status       tinyint     default 0  not null comment '处理状态0-未处理，1-已处理',
    market_id    int                    null comment '市场id'
)
    comment '建议' engine = MyISAM;

INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (1, 'aaa', '2017-01-19 13:52:29', 69, null, null, null, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (2, '???', '2017-02-07 08:56:19', 312, '/Uploads/2017/0207/sgrwjs4frgmgx.jpeg', '/Uploads/2017/0207/e8xh59dmlxa4f.jpeg', '', '', '', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (3, '???', '2017-02-07 08:56:24', 312, '/Uploads/2017/0207/sgrwjs4frgmgx.jpeg', '/Uploads/2017/0207/e8xh59dmlxa4f.jpeg', '', '', '', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (4, '???', '2017-02-07 08:56:26', 312, '/Uploads/2017/0207/sgrwjs4frgmgx.jpeg', '/Uploads/2017/0207/e8xh59dmlxa4f.jpeg', '', '', '', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (5, '????', '2017-02-07 09:05:27', 312, '/Uploads/2017/0207/y9glkl8yudmad.jpeg', '', '', '', '', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (6, 'Asf', '2017-02-09 14:20:42', 311, null, null, null, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (7, 'Sdfdsg', '2017-02-09 15:11:20', 311, null, null, null, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (8, 'Test', '2017-02-09 15:11:58', 311, null, null, null, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (9, 'Test again', '2017-02-09 15:13:04', 311, null, null, null, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (10, 'Shit', '2017-02-09 15:18:00', 311, null, null, null, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (11, 'Fuck', '2017-02-09 15:22:48', 311, '/Uploads/2017/0209/yr5ur9u59uiir.jpeg', null, null, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (12, 'Five pic', '2017-02-09 15:24:03', 311, '/Uploads/2017/0209/yo9eh7j5vzhdv.jpeg', '/Uploads/2017/0209/n6f2kp6ac6bi1.jpeg', '/Uploads/2017/0209/a8qas0qg9p8sh.jpeg', '/Uploads/2017/0209/stkrdarcg67i7.jpeg', '/Uploads/2017/0209/s411qwc9x4gl8.jpeg', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (13, '????', '2017-02-09 17:16:29', 311, '/Uploads/2017/0209/gsle6csk5z8fr.jpg', '', '', '', '', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (14, '123', '2017-02-10 16:46:14', 353, '/Uploads/2017/0210/ryelxdqarxl4u.jpeg', null, null, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (15, '??????????', '2017-02-13 10:59:00', 354, 'null', 'null', 'null', 'null', 'null', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (16, 'Test several pics??????', '2017-02-17 17:15:25', 353, '/Uploads/2017/0217/amjc89x5uivvu.jpeg', '/Uploads/2017/0217/pmr8iqk1uo0ev.jpeg', '/Uploads/2017/0217/m0ctx3g09k8pp.jpeg', '/Uploads/2017/0217/v2u0v11yzq42j.jpeg', '/Uploads/2017/0217/h8uc734sg4aoi.jpeg', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (17, '????', '2017-02-17 17:32:15', 354, '/Uploads/2017/0217/hctcfzcci6c1x.jpeg', '/Uploads/2017/0217/9ftjpxklqj7ct.jpeg', '/Uploads/2017/0217/jfg5wpynzaeba.jpeg', '/Uploads/2017/0217/719lcuydaqnao.jpeg', '/Uploads/2017/0217/uw6vfhnd6y55v.jpeg', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (18, '????', '2017-02-17 17:33:22', 354, '/Uploads/2017/0217/hctcfzcci6c1x.jpeg', '/Uploads/2017/0217/9ftjpxklqj7ct.jpeg', '/Uploads/2017/0217/jfg5wpynzaeba.jpeg', '/Uploads/2017/0217/719lcuydaqnao.jpeg', '/Uploads/2017/0217/uw6vfhnd6y55v.jpeg', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (19, '??', '2017-02-25 10:08:46', 354, '/Uploads/2017/0225/plco367jgux2l.jpeg', '', '', '', '', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (20, '??', '2017-02-25 10:13:38', 354, '/Uploads/2017/0225/62ra7s0qa68cn.jpeg', '', '', '', '', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (21, 'qsprs', '2017-02-27 15:39:30', 162, '/Uploads/2017/0227/90qsl3y9wy2zz.png', '/Uploads/2017/0227/11i4nelo11dcf.png', '/Uploads/2017/0227/mfkq7cygffatt.jpeg', '/Uploads/2017/0227/tpuoaaq6t0qb0.jpeg', '/Uploads/2017/0227/82dvy0x21ywsr.png', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (22, 'gyuu', '2017-02-28 17:49:18', 162, '/Uploads/2017/0228/3kp2srpbd5gkl.jpeg', '', '', '', '', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (23, 'udhfhfjfidjdjudd', '2017-03-01 13:54:28', 162, 'null', 'null', 'null', 'null', 'null', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (24, 'ddff', '2017-03-01 16:45:57', 162, 'null', 'null', 'null', 'null', 'null', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (25, '??', '2017-03-07 17:38:36', 162, '/Uploads/2017/0307/8za7azgazqli9.jpeg', '/Uploads/2017/0307/51r8ja34si2ar.jpeg', '/Uploads/2017/0307/7cmrwrn858fzt.jpeg', '/Uploads/2017/0307/b9sfny72mo88u.jpeg', '', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (26, 'Test ', '2017-03-17 15:01:30', 364, '/Uploads/2017/0317/chn464nsmh801.jpeg', '/Uploads/2017/0317/lpk70l5u2jvez.jpeg', null, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (27, 'aaaaa', '2017-03-17 15:05:47', 363, '/Uploads/2017/0317/xk7uw41m42pxt.png', '/Uploads/2017/0317/w7wjocoftlqod.jpeg', '', '', '', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (28, 'aaaa', '2017-03-17 15:08:18', 363, '/Uploads/2017/0317/og4pnbnsi3pzw.jpg', '', '', '', '', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (29, 'aaaa', '2017-03-17 15:11:36', 363, '/Uploads/2017/0317/fcjbi7h17asfv.jpeg', '/Uploads/2017/0317/re6b0jijvve73.jpeg', '', '', '', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (30, 'cab', '2017-03-17 17:55:15', 363, '/Uploads/2017/0317/5uzrzyee1w3ob.jpeg', '', '', '', '', null, null, null, null, 0, null);
INSERT INTO coldchain_sys_admin.proposal (id, content, add_time, pid, photo_one, photo_two, photo_three, photo_four, photo_five, update_time, remark, process_id, process_name, status, market_id) VALUES (31, '??', '2017-03-20 15:54:25', 162, null, null, null, null, null, null, null, null, null, 0, null);