create table user
(
    user_id                     int(10) auto_increment comment '表id'
        primary key,
    email                       varchar(60)    default ''        null comment '邮件',
    password                    varchar(255)   default ''        null comment '密码',
    company_id                  bigint                           null,
    is_admin                    int(4)         default 0         null,
    sex                         tinyint(1)     default 0         null comment '0 保密 1 男 2 女',
    birthday                    int            default 0         null comment '生日',
    user_money                  decimal(10, 2) default 0.00      null comment '用户金额',
    frozen_money                decimal(10, 2) default 0.00      null comment '冻结金额',
    distribut_money             decimal(10, 2) default 0.00      null comment '累积分佣金额',
    pay_points                  int(10)        default 0         null comment '消费积分',
    paypwd                      varchar(128)                     null comment '支付密码',
    reg_time                    int(10)        default 0         null comment '注册时间',
    last_login                  int            default 0         null comment '最后登录时间',
    last_ip                     varchar(15)    default ''        null comment '最后登录ip',
    qq                          varchar(20)    default ''        null comment 'QQ',
    mobile                      varchar(20)    default ''        null comment '手机号码',
    mobile_validated            tinyint(3)     default 0         null comment '是否验证手机',
    head_pic                    varchar(255)   default ''        null comment '头像',
    bank_name                   varchar(150)                     null comment '银行名称',
    bank_card                   varchar(50)                      null comment '银行账号',
    realname                    varchar(50)                      null comment '用户真实姓名',
    idcard                      varchar(100)                     null comment '身份证号',
    email_validated             tinyint(1)     default 0         null comment '是否验证电子邮箱',
    nickname                    varchar(50)    default ''        null comment '第三方返回昵称',
    level                       tinyint(1)     default 1         null comment '会员等级',
    grade                       int(4)                           null,
    discount                    decimal(10, 2) default 1.00      null comment '会员折扣，默认1不享受',
    total_amount                decimal(10, 2) default 0.00      null comment '消费累计额度',
    is_lock                     tinyint(1)     default 0         null comment '是否被锁定冻结',
    is_distribut                tinyint(1)     default 0         null comment '是否为分销商 0 否 1 是',
    first_leader                int            default 0         null comment '第一个上级',
    second_leader               int            default 0         null comment '第二个上级',
    third_leader                int            default 0         null comment '第三个上级',
    token                       varchar(64)    default ''        null comment '用于app 授权类似于session_id',
    underling_number            int(5)         default 0         null comment '用户下线数',
    message_mask                bit(6)         default b'111111' null comment '消息掩码',
    push_id                     varchar(30)    default ''        null comment '推送id',
    distribut_level             tinyint(2)     default 0         null comment '分销商等级',
    xcx_qrcode                  varchar(255)                     null comment '小程序专属二维码',
    is_store_member             int            default 0         null comment '属于哪个店铺的会员',
    is_entry                    tinyint(1)     default 0         null comment '0平常注册，1微信注册绑定，2微信账号关联',
    manifesto                   varchar(255)   default ''        null comment '个人签名',
    distribut_withdrawals_money decimal(10, 2) default 0.00      null comment '累积分销佣金提现',
    create_time                 datetime                         null,
    create_by                   varchar(32)                      null,
    update_time                 datetime                         null,
    update_by                   varchar(32)                      null,
    identity                    varchar(6)                       null comment '身份 seller user  admin',
    code                        varchar(32)                      null comment '用户code',
    lead_id                     int(10)        default 0         null comment '上级id',
    user_address                varchar(255)                     null comment '用户地址'
);

create index email
    on user (email);

create index mobile
    on user (mobile_validated);

INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (60, '', '{bcrypt}$2a$10$hnTjGjydgc9nGlfVcAVJ/.Iqkhw9vICFWqBQJiesORaC8F7CCFgiW', null, 1, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604041304, 0, '', '', '13058140233', 0, '', null, null, null, null, 0, '13058140233', 1, null, 1.00, 0.00, 0, 1, 0, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (61, '', '{bcrypt}$2a$10$FQ9sDCMK2jxms98NaSRIcu.Y6KQBrlcErZ14DSik59k5q0Gt0rGMO', null, 0, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604041408, 0, '', '', '13086748596', 0, '', null, null, null, null, 0, '13086748596', 1, null, 1.00, 0.00, 0, 1, 60, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (62, '', '{bcrypt}$2a$10$sC76o9fn/9SD/p35I1cD0uh2LZO3r5Gc4BqEFCo0jU/75MPdb02ue', null, 1, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604051780, 0, '', '', '13052635263', 0, '', null, null, null, null, 0, '13052635263', 1, null, 1.00, 0.00, 0, 1, 60, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (63, '', '{bcrypt}$2a$10$oloCk7pwETg.4zlAt0K5hOTn8tDeQ9LyVlsv5T0rMxs9FlEkOmZ5a', null, 1, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604051796, 0, '', '', '13057485145', 0, '', null, null, null, null, 0, '13057485145', 1, null, 1.00, 0.00, 0, 1, 60, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (64, '', '{bcrypt}$2a$10$EFHkT.p0Xnwopi4RKz.95unp/0aT1LVoH1K8PnSHxaOVPImvWzpJe', null, 1, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604053051, 0, '', '', '15889781738', 0, '', null, null, null, null, 0, '15889781738', 1, null, 1.00, 0.00, 0, 1, 60, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (65, '', '{bcrypt}$2a$10$nGvdCi8eYX.IQEaPPLHcEO53YkGvIqiA3ONiH0cvweYim5TCjpqUu', null, 0, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604054692, 0, '', '', '13674859685', 0, '', null, null, null, null, 0, '13674859685', 1, null, 1.00, 0.00, 0, 1, 64, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, 'XrO7_u2020103000065', 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (66, '', '{bcrypt}$2a$10$IwG3Tk/o6JH7rtQ.FASW9ev4/X7.BE.iXuwjoxHD232RONwe8kGka', null, 0, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604055000, 0, '', '', '18685968596', 0, '', null, null, null, null, 0, '18685968596', 1, null, 1.00, 0.00, 0, 1, 64, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, 'wgyw_u2020103000066', 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (78, '', '{bcrypt}$2a$10$qo3VAt.RTKFtD4uKc7sGKO0h5SgGeHGSyUIeFrasve8Uh4t.bUU1u', null, 0, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604055620, 0, '', '', '13410559097', 0, '', null, null, null, null, 0, '13410559097', 1, null, 1.00, 0.00, 0, 1, 64, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, 'UcGU_u2020103000076', 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (80, '', '{bcrypt}$2a$10$voJXry.T4c5iwjF27tbZjeQVtiQwFWEM2hW5Yh56kmSL.kx2JGmpa', null, 1, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604057940, 0, '', '', '15555085266', 0, '', null, null, null, null, 0, '15555085266', 1, null, 1.00, 0.00, 0, 1, 0, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (81, '', '{bcrypt}$2a$10$bxJqsI8RuCLxtjTQoIti/.rpdJxmjpaKrgp9zIJiKxIGlERdNL0H2', null, 0, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604058086, 0, '', '', '14198894444', 0, '', null, null, null, null, 0, '14198894444', 1, null, 1.00, 0.00, 0, 1, 80, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, '6TdP_u2020103000081', 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (82, '18687269789@163.com', '{bcrypt}$2a$10$FQw8jO9//zX5nGeNCDJ7auVX9kJvUxOs6q2S7ZKKfE0EdM5utmxgu', null, 0, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604059016, 0, '', '', '18687269789', 0, '', null, null, null, null, 0, '18687269789', 1, null, 1.00, 0.00, 0, 1, 60, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, 'apBJ_u2020103000082', 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (83, '18687369789@163.com', '{bcrypt}$2a$10$tuFkVW4ldXdMeocDflEpTOdpwylbWAeTj8X6uwksBO2i7824H.BkO', null, 0, 0, 0, 0.00, 0.00, 0.00, 0, null, 0, 0, '', '', '18687259632', 0, '', null, null, 'dddd', null, 0, '18687268526', 1, null, 1.00, 0.00, 0, 0, 0, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, '2020-10-30 20:18:56', null, null, null, 'SELLER', 'HeHA_u2020103000083', 60, 'dddads');
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (84, '', '{bcrypt}$2a$10$B4HYfAc9fKL1CqpYbs.wEO5XIXADkCrbnpX17/CJJYEPGFQGNMqVq', null, 0, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604109299, 0, '', '', '13612868436', 0, '', null, null, null, null, 0, '13612868436', 1, null, 1.00, 0.00, 0, 1, 64, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, 'WJNC_u2020103100084', 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (85, '', '{bcrypt}$2a$10$SjDxy6pSUGyVjtsJVsI3suRq2L43G5LUyHYqY/6DvCVJIBdgFx4Ci', null, 0, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604121569, 0, '', '', '13105285520', 0, '', null, null, null, null, 0, '13105285520', 1, null, 1.00, 0.00, 0, 1, 64, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, 'NStM_u2020103100085', 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (86, '', '{bcrypt}$2a$10$OMOk7r0aIQFSe7MB7Tt58ONuVaulMNG2PH7rZzeExO3Lps.8IAul6', null, 1, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604122773, 0, '', '', '18387879090', 0, '', null, null, null, null, 0, '18387879090', 1, null, 1.00, 0.00, 0, 1, 0, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (87, '', '{bcrypt}$2a$10$kroXZ4RCyTHWaxjy7topo.9UEGeqor/GzDgPaDdr7hYRyzDOjJXG2', null, 1, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604123025, 0, '', '', '18687654321', 0, '', null, null, null, null, 0, '18687654321', 1, null, 1.00, 0.00, 0, 1, 0, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (88, '', '{bcrypt}$2a$10$ISBe.Q62O.OIFo/CaJ7Yo.0ddcUgp93j0nf4QjZaZniF9gqZsa95C', null, 0, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604123306, 0, '', '', '13052415263', 0, '', null, null, null, null, 0, '13052415263', 1, null, 1.00, 0.00, 0, 1, 87, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, 'Vidm_u2020103100088', 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (89, '', '{bcrypt}$2a$10$SAIJUzfeIVZbYygZ0rL/PeHrTxGAQSzTpmoKjTp0wveNyYE6VwFG6', null, 1, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604131231, 0, '', '', '13098765412', 0, '', null, null, null, null, 0, '13098765412', 1, null, 1.00, 0.00, 0, 1, 0, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (90, '', '{bcrypt}$2a$10$zzObtw/o1KQD2osjBt/mwuiqbSvHyXmPhyH/B3Ozk8PSpMMfzQgJe', null, 0, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604132018, 0, '', '', '13097888881', 0, '', null, null, null, null, 0, '13097888881', 1, null, 1.00, 0.00, 0, 1, 89, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, '4uVz_u2020103100090', 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (91, '', '{bcrypt}$2a$10$lZDOO/IgweUwrKZ7EHqTAO5BYRG/V2goFfOVL2V6vAzBFmylgBXKe', null, 0, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604132768, 0, '', '', '15889781732', 0, '', null, null, null, null, 0, '15889781732', 1, null, 1.00, 0.00, 0, 1, 64, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, 'lsIo_u2020103100091', 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (92, '', '{bcrypt}$2a$10$Z45YC54Mm25G2t4QkjBty.2POgn5.M1biC.I9u1vXfFFLn7rE3y92', null, 1, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604284920, 0, '', '', '17674181052', 0, '', null, null, null, null, 0, '17674181052', 1, null, 1.00, 0.00, 0, 1, 0, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (93, '', '{bcrypt}$2a$10$bOqNK5FUpE4Q2zVe9zRa5Odyu8maIRgtcDUGYU7U5TUaTU3/0cvie', null, 1, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604299172, 0, '', '', '13068197971', 0, '', null, null, null, null, 0, '13068197971', 1, null, 1.00, 0.00, 0, 1, 0, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (94, '', '{bcrypt}$2a$10$w90J/8IjRij9ynO1mwCGYugEG02dZo6m5Ijq3sWzBN/IK8IH/AMqu', null, 0, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604299682, 0, '', '', '13055978524', 0, '', null, null, null, null, 0, '13055978524', 1, null, 1.00, 0.00, 0, 1, 92, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, '3TVc_u2020110200094', 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (96, '186@163.com', '{bcrypt}$2a$10$VKSYFJ7oqMeuMbRpURFLxOHT1SpkJB6ugK.iNkPky2OarwTdf1Mjq', null, 0, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604304207, 1604304222, '', '', '18687568524', 0, '', null, null, null, null, 0, '18687568524', 1, null, 1.00, 0.00, 0, 1, 60, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, 'ezsA_u2020110200096', 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (97, '', '{bcrypt}$2a$10$YPLxkh4UhfCTMgybndlBj.spSVvAnyMrtD32HBhvEX9nVW7BoQl..', null, 0, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604304992, 0, '', '', '17674181010', 0, '', null, null, null, null, 0, '17674181010', 1, null, 1.00, 0.00, 0, 1, 92, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, 'zZvn_u2020110200097', 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (98, '', '{bcrypt}$2a$10$SXlhHAFMzrzaLeERj1FWdOSTxPRAzgeJLbWJUhprwMspPnB2BFeOK', null, 1, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604385011, 0, '', '', '18897892621', 0, '', null, null, null, null, 0, '18897892621', 1, null, 1.00, 0.00, 0, 1, 0, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, null, 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (99, '', '{bcrypt}$2a$10$CqMuUblViUbcrc9iomyTXuCsDur.ukBJGGKjwY.WEZqQHVY3cMR06', null, 0, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604385632, 0, '', '', '13052415296', 0, '', null, null, null, null, 0, '13052415296', 1, null, 1.00, 0.00, 0, 1, 98, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, 'EZqo_u2020110300099', 0, null);
INSERT INTO coldchain_user.user (user_id, email, password, company_id, is_admin, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, grade, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money, create_time, create_by, update_time, update_by, identity, code, lead_id, user_address) VALUES (100, '', '{bcrypt}$2a$10$IRnqsNArW3YvzqYLasG4qeH1Uo5Y202craqQFdjmgURy.3ArwoqY.', null, 0, 0, 0, 0.00, 0.00, 0.00, 0, null, 1604388936, 0, '', '', '13052410202', 0, '', null, null, null, null, 0, '13052410202', 1, null, 1.00, 0.00, 0, 1, 98, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00, null, null, null, null, null, 'qVnQ_u2020110300100', 0, null);