create table sys_dept
(
    dept_id             bigint auto_increment comment '部门id'
        primary key,
    parent_id           bigint      default 0   null comment '父部门id',
    ancestors           varchar(50) default ''  null comment '祖级列表',
    dept_name           varchar(30) default ''  null comment '部门名称',
    responsibility      varchar(255)            null comment '部门职责',
    enterprise_location varchar(255)            null comment '企业地址',
    order_num           int(4)      default 0   null comment '显示顺序',
    leader              varchar(20)             null comment '负责人',
    phone               varchar(11)             null comment '联系电话',
    email               varchar(50)             null comment '邮箱',
    setmeal_type        varchar(64)             null comment '套餐类型',
    status              char        default '0' null comment '部门状态（0正常 1停用）',
    del_flag            char        default '0' null comment '删除标志（0代表存在 2代表删除）',
    create_by           varchar(64) default ''  null comment '创建者',
    create_time         datetime                null comment '创建时间',
    update_by           varchar(64) default ''  null comment '更新者',
    update_time         datetime                null comment '更新时间'
)
    comment '部门表';

INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (100, 0, '0', '新时空智能', null, null, 0, '管理员', '15888888888', 'ry@qq.com', null, '0', '0', 'admin', '2018-03-16 11:33:00', 'admin', '2020-08-07 17:54:50');
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (101, 100, '0,100', '深圳总公司测试', null, null, 1, 'aaa', '', '', null, '0', '0', 'admin', '2018-03-16 11:33:00', 'admin', '2020-08-03 14:58:21');
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (102, 100, '0,100', '北京分公司', null, null, 2, '管理员', '15888888888', 'ry@qq.com', null, '0', '0', 'admin', '2018-03-16 11:33:00', 'ry', '2018-03-16 11:33:00');
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (103, 101, '0,100,101', '研发部门', null, null, 1, '管理员', '15888888888', 'ry@qq.com', null, '0', '0', 'admin', '2018-03-16 11:33:00', 'ry', '2018-03-16 11:33:00');
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (104, 101, '0,100,101', '市场部门', null, null, 2, '管理员', '15888888888', 'ry@qq.com', null, '0', '0', 'admin', '2018-03-16 11:33:00', 'ry', '2018-03-16 11:33:00');
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (105, 101, '0,100,101', '测试部门', null, null, 3, '管理员', '15888888888', 'ry@qq.com', null, '0', '0', 'admin', '2018-03-16 11:33:00', 'ry', '2018-03-16 11:33:00');
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (106, 101, '0,100,101', '财务部门', null, null, 4, '管理员', '15888888888', 'ry@qq.com', null, '0', '0', 'admin', '2018-03-16 11:33:00', 'ry', '2018-03-16 11:33:00');
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (107, 101, '0,100,101', '运维部门', null, null, 5, '管理员', '15888888888', 'ry@qq.com', null, '0', '0', 'admin', '2018-03-16 11:33:00', 'ry', '2018-03-16 11:33:00');
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (108, 102, '0,100,102', '市场部门', null, null, 1, '管理员', '15888888888', 'ry@qq.com', null, '0', '0', 'admin', '2018-03-16 11:33:00', 'ry', '2018-03-16 11:33:00');
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (109, 102, '0,100,102', '财务部门', null, null, 2, '管理员', '15888888888', 'ry@qq.com', null, '0', '2', 'admin', '2018-03-16 11:33:00', 'ry', '2018-03-16 11:33:00');
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (200, 100, '0,100', '1', null, null, 0, '1', null, null, null, '0', '2', '', '2020-07-29 13:13:19', '', null);
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (201, 0, '', 'ccc', null, null, 0, 'aaa', '', '', null, '', '2', '', '2020-07-29 13:43:12', 'admin', '2020-07-29 13:44:24');
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (202, 100, '0,100', '6', null, null, 0, '6', null, null, null, '0', '2', '', '2020-07-30 11:12:36', '', null);
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (203, 100, '0,100', 'dd', null, null, 0, 'dd', null, null, null, '0', '2', '', '2020-08-03 11:05:44', '', null);
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (204, 0, '', '7878', null, null, 0, '7878', null, null, null, '0', '2', '', '2020-08-03 11:10:39', '', null);
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (205, 100, '0,100', '谷歌', null, null, 0, '滚滚滚', null, null, null, '0', '2', '', '2020-08-03 17:16:32', '', null);
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (206, 0, '', '哈哈哈', null, null, 0, '', '', '111@qq.com', null, '0', '0', '', '2020-08-03 17:33:01', 'admin', '2020-08-06 15:33:35');
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (208, 0, '', '测试企业', null, null, 0, '张三', '12321231', '3333@qq.com', null, '0', '0', 'admin', '2020-08-06 15:34:37', '', null);
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (209, 0, '', '123', null, null, 0, '123', '123', '123', null, '0', '0', '', '2020-08-07 17:43:06', '', null);
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (210, 0, '', '1', null, null, 0, '4', '5', '2', null, '0', '0', '', '2020-08-07 17:55:19', '', null);
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (211, 0, '', '0', null, null, 0, '7', '6', '9', null, '0', '0', '', '2020-08-07 18:04:04', '', null);
INSERT INTO coldchain_sys_admin.sys_dept (dept_id, parent_id, ancestors, dept_name, responsibility, enterprise_location, order_num, leader, phone, email, setmeal_type, status, del_flag, create_by, create_time, update_by, update_time) VALUES (214, 208, ',208', '哈哈哈121', 'aaaaaaaaaaaaaaa', null, 0, '哈哈哈1111', null, '111@qq.com', null, '', '0', '', '2020-08-07 18:09:38', '', null);