
package com.coldchain.project.ocpcl.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "ProvisioningPortType_v1_0", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface OcpClientWebService {


    /**
     * 测试链接
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.EchoResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "Echo")
    @WebResult(name = "EchoResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public EchoResponse echo(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "EchoRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    EchoRequest request)
            throws FaultMessage
    ;

    /**
     * 获取用户配置
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.GetUserProfileResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "GetUserProfile")
    @WebResult(name = "GetUserProfileResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public GetUserProfileResponse getUserProfile(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "GetUserProfileRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    GetUserProfileRequest request)
            throws FaultMessage
    ;

    /**
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "OperationPoll")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse operationPoll(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "OperationPollRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    OperationPollRequest request)
            throws FaultMessage
    ;

    /**
     * 激活设备
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "OperationActivate")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse operationActivate(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "ActivateRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    ActivateRequest request)
            throws FaultMessage
    ;

    /**
     * 更改设备
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "OperationChange")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse operationChange(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "ChangeRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    ChangeRequest request)
            throws FaultMessage
    ;

    /**
     * 停止设备
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "OperationSuspend")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse operationSuspend(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "SuspendRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    SuspendRequest request)
            throws FaultMessage
    ;

    /**
     * 恢复设备
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "OperationUnsuspend")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse operationUnsuspend(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "UnsuspendRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    UnsuspendRequest request)
            throws FaultMessage
    ;

    /**
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "OperationBlock")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse operationBlock(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "BlockRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    BlockRequest request)
            throws FaultMessage
    ;

    /**
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "OperationUnblock")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse operationUnblock(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "UnblockRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    UnblockRequest request)
            throws FaultMessage
    ;

    /**
     * 撤销设备
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "OperationDeactivate")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse operationDeactivate(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "DeactivateRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    DeactivateRequest request)
            throws FaultMessage
    ;

    /**
     * 替换设备
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "OperationSwap")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse operationSwap(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "SwapRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    SwapRequest request)
            throws FaultMessage
    ;

    /**
     * 设备列表
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "ListSubscribers")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse listSubscribers(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "ListSubscribersRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    ListSubscribersRequest request)
            throws FaultMessage
    ;

    /**
     * 企业列表
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "ListEnterprises")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse listEnterprises(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "ListEnterprisesRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    ListEnterprisesRequest request)
            throws FaultMessage
    ;

    /**
     * 组织列表
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "ListOrganizations")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse listOrganizations(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "ListOrganizationsRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    ListOrganizationsRequest request)
            throws FaultMessage
    ;

    /**
     * 账号列表
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "ListAccounts")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse listAccounts(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "ListAccountsRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    ListAccountsRequest request)
            throws FaultMessage
    ;

    /**
     * 子账号列表
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "ListSubaccounts")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse listSubaccounts(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "ListSubaccountsRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    ListSubaccountsRequest request)
            throws FaultMessage
    ;

    /**
     * 创建组织
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "CreateOrganization")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse createOrganization(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "CreateOrganizationRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    CreateOrganizationRequest request)
            throws FaultMessage
    ;

    /**
     * 创建账号
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "CreateAccount")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse createAccount(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "CreateAccountRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    CreateAccountRequest request)
            throws FaultMessage
    ;

    /**
     * 创建子账号
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "CreateSubaccount")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse createSubaccount(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "CreateSubaccountRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    CreateSubaccountRequest request)
            throws FaultMessage
    ;

    /**
     * 更新组织
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "UpdateOrganization")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse updateOrganization(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "UpdateOrganizationRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    UpdateOrganizationRequest request)
            throws FaultMessage
    ;

    /**
     * 更新账号
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "UpdateAccount")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse updateAccount(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "UpdateAccountRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    UpdateAccountRequest request)
            throws FaultMessage
    ;

    /**
     * 更新子账号
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "UpdateSubaccount")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse updateSubaccount(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "UpdateSubaccountRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    UpdateSubaccountRequest request)
            throws FaultMessage
    ;

    /**
     * 时区列表
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "ListZones")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse listZones(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "ListZonesRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    ListZonesRequest request)
            throws FaultMessage
    ;

    /**
     * 列表消息筛选器配置文件
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "ListMessageFilterProfiles")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse listMessageFilterProfiles(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "ListMessageFilterProfilesRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    ListMessageFilterProfilesRequest request)
            throws FaultMessage
    ;

    /**
     * 资产类型列表
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "ListAssetTypes")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse listAssetTypes(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "ListAssetTypesRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    ListAssetTypesRequest request)
            throws FaultMessage
    ;

    /**
     * 交货计划列表
     *
     * @param header  请求头部分
     * @param request 请求体部分
     * @return returns com.coldchain.project.ocpcl.webservice.OperationResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "ListDeliveryPlans")
    @WebResult(name = "OperationResponse", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "response")
    public OperationResponse listDeliveryPlans(
            @WebParam(name = "Header", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "header")
                    Header header,
            @WebParam(name = "ListDeliveryPlansRequest", targetNamespace = "http://www.orbcomm.com/wsdl/OrbcommProvisioning-v1.0", partName = "request")
                    ListDeliveryPlansRequest request)
            throws FaultMessage
    ;

}
